CC=clang

SRC=$(wildcard Spec/*.c)
CFLAGS=-fblocks -IElara -IInclude -g
LFLAGS=-lelara -LElara
UNAME_S=$(shell uname -s)
ifeq ($(UNAME_S),Linux)
	LFLAGS += -lBlocksRuntime
endif

OBJ=$(SRC:.c=.o)

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)

ElaraSpec: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LFLAGS)

.PHONY: clean spec

spec:
	./ElaraSpec

clean:
	rm -rf Spec/*.o
